-- H2 compatibility supplement for benchmark integration tests.
-- Some benchmark entities use PostgreSQL-specific column definitions such as JSONB and VECTOR,
-- which are not created by Hibernate against H2. Keep this file minimal and test-only.

CREATE TABLE IF NOT EXISTS benchmark_quality_script (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL,
    video_id BIGINT NOT NULL,
    analysis_id BIGINT NOT NULL,
    script_content CLOB NOT NULL,
    script_type VARCHAR(50),
    industry VARCHAR(50),
    scene_type VARCHAR(50),
    quality_score DECIMAL(5,2) NOT NULL,
    engagement_rate DECIMAL(5,2),
    viral_score DECIMAL(5,2),
    completion_rate DECIMAL(5,2),
    ai_rating DECIMAL(5,2),
    likes_count INTEGER DEFAULT 0,
    comments_count INTEGER DEFAULT 0,
    shares_count INTEGER DEFAULT 0,
    collections_count INTEGER DEFAULT 0,
    views_count INTEGER DEFAULT 0,
    video_duration INTEGER,
    key_features CLOB,
    creative_elements CLOB,
    hook_strategy CLOB,
    content_structure CLOB,
    embedding_vector CLOB,
    reference_count INTEGER DEFAULT 0,
    last_referenced_at TIMESTAMP,
    create_time TIMESTAMP,
    update_time TIMESTAMP,
    deleted INTEGER DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_quality_script_owner ON benchmark_quality_script(owner_id, deleted);
CREATE INDEX IF NOT EXISTS idx_quality_script_video ON benchmark_quality_script(video_id, deleted);
CREATE INDEX IF NOT EXISTS idx_quality_script_score ON benchmark_quality_script(quality_score, deleted);

CREATE TABLE IF NOT EXISTS benchmark_script_similarity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL,
    source_script_id BIGINT NOT NULL,
    target_script_id BIGINT NOT NULL,
    similarity_score DECIMAL(5,4) NOT NULL,
    similarity_type VARCHAR(20) DEFAULT 'semantic',
    create_time TIMESTAMP,
    deleted INTEGER DEFAULT 0,
    CONSTRAINT uk_script_similarity UNIQUE (source_script_id, target_script_id, deleted)
);

CREATE INDEX IF NOT EXISTS idx_similarity_source ON benchmark_script_similarity(source_script_id, similarity_score);
CREATE INDEX IF NOT EXISTS idx_similarity_target ON benchmark_script_similarity(target_script_id, deleted);
