-- H2 compatibility supplement for benchmark integration tests.
-- Some benchmark entities use PostgreSQL-specific column definitions such as JSONB and VECTOR,
-- which are not created by Hibernate against H2. Keep this file minimal and test-only.

CREATE TABLE IF NOT EXISTS benchmark_quality_script (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL,
    video_id BIGINT NOT NULL,
    analysis_id BIGINT NOT NULL,
    script_content CLOB NOT NULL,
    script_type VARCHAR(50),
    industry VARCHAR(50),
    scene_type VARCHAR(50),
    quality_score DECIMAL(5,2) NOT NULL,
    engagement_rate DECIMAL(5,2),
    viral_score DECIMAL(5,2),
    completion_rate DECIMAL(5,2),
    ai_rating DECIMAL(5,2),
    likes_count INTEGER DEFAULT 0,
    comments_count INTEGER DEFAULT 0,
    shares_count INTEGER DEFAULT 0,
    collections_count INTEGER DEFAULT 0,
    views_count INTEGER DEFAULT 0,
    video_duration INTEGER,
    key_features CLOB,
    creative_elements CLOB,
    hook_strategy CLOB,
    content_structure CLOB,
    embedding_vector CLOB,
    reference_count INTEGER DEFAULT 0,
    last_referenced_at TIMESTAMP,
    create_time TIMESTAMP,
    update_time TIMESTAMP,
    deleted INTEGER DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_quality_script_owner ON benchmark_quality_script(owner_id, deleted);
CREATE INDEX IF NOT EXISTS idx_quality_script_video ON benchmark_quality_script(video_id, deleted);
CREATE INDEX IF NOT EXISTS idx_quality_script_score ON benchmark_quality_script(quality_score, deleted);

CREATE TABLE IF NOT EXISTS benchmark_script_similarity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL,
    source_script_id BIGINT NOT NULL,
    target_script_id BIGINT NOT NULL,
    similarity_score DECIMAL(5,4) NOT NULL,
    similarity_type VARCHAR(20) DEFAULT 'semantic',
    create_time TIMESTAMP,
    deleted INTEGER DEFAULT 0,
    CONSTRAINT uk_script_similarity UNIQUE (source_script_id, target_script_id, deleted)
);

CREATE INDEX IF NOT EXISTS idx_similarity_source ON benchmark_script_similarity(source_script_id, similarity_score);
CREATE INDEX IF NOT EXISTS idx_similarity_target ON benchmark_script_similarity(target_script_id, deleted);

CREATE TABLE IF NOT EXISTS compliance_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_code VARCHAR(64) NOT NULL UNIQUE,
    category VARCHAR(32) NOT NULL,
    sub_category VARCHAR(32),
    rule_name VARCHAR(128) NOT NULL,
    description CLOB NOT NULL,
    severity VARCHAR(16) NOT NULL,
    punishment CLOB,
    examples CLOB,
    keywords CLOB,
    patterns CLOB,
    embedding CLOB,
    source_url CLOB,
    effective_date DATE,
    status INTEGER NOT NULL DEFAULT 1,
    deleted INTEGER NOT NULL DEFAULT 0,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_compliance_rule_category ON compliance_rule(category, sub_category);
CREATE INDEX IF NOT EXISTS idx_compliance_rule_severity ON compliance_rule(severity);
CREATE INDEX IF NOT EXISTS idx_compliance_rule_status ON compliance_rule(status, deleted);

CREATE TABLE IF NOT EXISTS compliance_keyword (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword VARCHAR(128) NOT NULL,
    category VARCHAR(32) NOT NULL,
    severity VARCHAR(16) NOT NULL,
    replacement VARCHAR(128),
    status INTEGER NOT NULL DEFAULT 1,
    deleted INTEGER NOT NULL DEFAULT 0,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_compliance_keyword_category ON compliance_keyword(category, severity);
CREATE INDEX IF NOT EXISTS idx_compliance_keyword_keyword ON compliance_keyword(keyword);

CREATE TABLE IF NOT EXISTS compliance_check_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    content_type VARCHAR(32) NOT NULL,
    content_id BIGINT,
    content_text CLOB,
    check_result VARCHAR(16) NOT NULL,
    matched_rules CLOB,
    risk_score DECIMAL(5,2),
    suggestions CLOB,
    check_duration_ms INTEGER,
    check_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_compliance_check_log_user ON compliance_check_log(user_id, check_time);
CREATE INDEX IF NOT EXISTS idx_compliance_check_log_content ON compliance_check_log(content_type, content_id);
CREATE INDEX IF NOT EXISTS idx_compliance_check_log_result ON compliance_check_log(check_result, check_time);

CREATE TABLE IF NOT EXISTS compliance_case (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id BIGINT NOT NULL,
    case_title VARCHAR(256) NOT NULL,
    case_content CLOB NOT NULL,
    violation_reason CLOB,
    punishment_result CLOB,
    case_source VARCHAR(128),
    case_date DATE,
    status INTEGER NOT NULL DEFAULT 1,
    deleted INTEGER NOT NULL DEFAULT 0,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_compliance_case_rule ON compliance_case(rule_id);
CREATE INDEX IF NOT EXISTS idx_compliance_case_date ON compliance_case(case_date);
