const ROUTE_LABELS: Record<string, string> = {
  '/admin/dashboard': '首页',
  '/org/dashboard': '机构工作台',
  '/talent/dashboard': '达人工作台',
  '/user/dashboard': '普通用户工作台',
  '/admin/profile': '个人中心',
  '/org/profile': '个人中心',
  '/talent/profile': '个人中心',
  '/user/profile': '个人中心',
  '/user/shortvideo': '我的短视频',
  '/user/shortvideo/create': 'AI 创作',
  '/user/shortvideo/planning': '脚本策划',
  '/user/shortvideo/materials': '素材准备',
  '/user/shortvideo/publish': '发布检查',
  '/admin/auth/users': '用户管理',
  '/admin/auth/roles': '角色管理',
  '/admin/auth/resources': '资源权限',
  '/admin/auth/login-logs': '登录日志',
  '/admin/douyin/accounts': '抖音账号',
  '/admin/douyin/videos': '视频列表',
  '/admin/live/sessions': '直播场次',
  '/admin/live/sessions/create': '新建场次',
  '/admin/live/scripts': '直播话术',
  '/admin/live/products': '直播商品',
  '/admin/live/ranking': '话术排行',
  '/admin/live/rhythm': '节奏配置',
  '/admin/live/history-compare': '版本对比',
  '/org/live/sessions': '机构直播场次',
  '/org/live/sessions/create': '新建场次',
  '/org/live/scripts': '直播话术',
  '/org/live/products': '直播商品',
  '/org/live/ranking': '话术排行',
  '/org/live/rhythm': '节奏配置',
  '/org/live/history-compare': '版本对比',
  '/org/live/reviews': '复盘审核',
  '/talent/live/sessions': '达人直播场次',
  '/talent/douyin/accounts': '抖音账号',
  '/talent/douyin/videos': '视频列表',
  '/org/product/list': '商品管理',
  '/org/product': '商品管理',
  '/org/product/sales-history': '销售记录',
  '/org/product/effectiveness': '话术效果',
  '/org/product/style-presets': '风格预设',
  '/org/product/readiness': '上播准备度',
  '/org/script/list': '话术脚本',
  '/org/script/violation-words': '违规词库',
  '/org/script/violation-check': '违规检测',
  '/org/script/templates': '话术模板',
  '/org/script/hybrid-search': '混合搜索',
  '/org/script/generation': '脚本生成',
  '/org/script/optimization': '脚本优化',
  '/admin/product/list': '商品管理',
  '/admin/product': '商品管理',
  '/admin/product/sales-history': '销售记录',
  '/admin/product/effectiveness': '话术效果',
  '/admin/product/style-presets': '风格预设',
  '/admin/product/readiness': '上播准备度',
  '/admin/script/list': '话术脚本',
  '/admin/script/violation-words': '违规词库',
  '/admin/script/violation-check': '违规检测',
  '/admin/script/templates': '话术模板',
  '/admin/script/hybrid-search': '混合搜索',
  '/admin/script/generation': '脚本生成',
  '/admin/script/optimization': '脚本优化',
  '/admin/shortvideo/projects': '短视频项目',
  '/talent/shortvideo': '达人短视频项目',
  '/talent/shortvideo/projects': '短视频项目',
  '/talent/shortvideo/collect': '账号采集',
  '/talent/shortvideo/accounts': '短视频账号',
  '/talent/shortvideo/viral-videos': '爆款视频库',
  '/talent/shortvideo/remake-templates': '改编模板',
  '/talent/shortvideo/dashboard': '短视频首页',
  '/talent/shortvideo/shot-list': '分镜设计',
  '/talent/shortvideo/material': '素材管理',
  '/talent/shortvideo/material-prepare': '素材准备',
  '/talent/shortvideo/material-production': '素材生产',
  '/talent/shortvideo/editing': '视频生成',
  '/talent/shortvideo/publish': '发布调度',
  '/talent/shortvideo/quality': '质量看板',
  '/talent/shortvideo/daily': '日排内容',
  '/talent/shortvideo/content-calendar': '内容日历',
  '/talent/shortvideo/hot-topics/create': '热点借势创作',
  '/talent/shortvideo/hot-topics': '热点话题',
  '/talent/shortvideo/drama': '剧情短视频',
  '/talent/shortvideo/viral-chain': '传播链分析',
  '/talent/shortvideo/competitor-monitor': '竞品监控',
  '/talent/shortvideo/effect-predict': '效果预测',
  '/talent/shortvideo/data-analysis': '数据分析',
  '/talent/shortvideo/insights': '洞见中心',
  '/talent/shortvideo/quick-generate': '快速生成',
  '/talent/shortvideo/script-planning': '脚本策划',
  '/talent/shortvideo/workbench': '项目工作台',
  '/talent/shortvideo/workflow-editor': '工作流编辑',
  '/talent/shortvideo/subtitles': '字幕编辑',
  '/talent/shortvideo/persona-fusion': '人设融合爆款',
  '/talent/shortvideo/ai-music': 'AI 配乐',
  '/talent/shortvideo/seo': 'SEO 优化',
  '/talent/shortvideo/seo-optimize': 'SEO 优化',
  '/talent/shortvideo/douyin-cookies': '抖音 Cookie 管理',
  '/talent/shortvideo/benchmark/accounts': '对标账号',
  '/talent/shortvideo/benchmark/videos': '对标视频',
  '/talent/shortvideo/benchmark/quality-scripts': '质量脚本库',
  '/talent/shortvideo/benchmark/recommendation': '脚本推荐',
  '/admin/shortvideo/collect': '账号采集',
  '/admin/shortvideo/accounts': '短视频账号',
  '/admin/shortvideo/viral-videos': '爆款视频库',
  '/admin/shortvideo/remake-templates': '改编模板',
  '/admin/shortvideo/dashboard': '短视频首页',
  '/admin/shortvideo/shot-list': '分镜设计',
  '/admin/shortvideo/material': '素材管理',
  '/admin/shortvideo/material-prepare': '素材准备',
  '/admin/shortvideo/material-production': '素材生产',
  '/admin/shortvideo/editing': '视频生成',
  '/admin/shortvideo/publish': '发布调度',
  '/admin/shortvideo/quality': '质量看板',
  '/admin/shortvideo/daily': '日排内容',
  '/admin/shortvideo/content-calendar': '内容日历',
  '/admin/shortvideo/hot-topics/create': '热点借势创作',
  '/admin/shortvideo/hot-topics': '热点话题',
  '/admin/shortvideo/drama': '剧情短视频',
  '/admin/shortvideo/viral-chain': '传播链分析',
  '/admin/shortvideo/competitor-monitor': '竞品监控',
  '/admin/shortvideo/effect-predict': '效果预测',
  '/admin/shortvideo/data-analysis': '数据分析',
  '/admin/shortvideo/insights': '洞见中心',
  '/admin/shortvideo/quick-generate': '快速生成',
  '/admin/shortvideo/script-planning': '脚本策划',
  '/admin/shortvideo/workbench': '项目工作台',
  '/admin/shortvideo/workflow-editor': '工作流编辑',
  '/admin/shortvideo/subtitles': '字幕编辑',
  '/admin/shortvideo/persona-fusion': '人设融合爆款',
  '/admin/shortvideo/ai-music': 'AI 配乐',
  '/admin/shortvideo/seo': 'SEO 优化',
  '/admin/shortvideo/seo-optimize': 'SEO 优化',
  '/admin/shortvideo/douyin-cookies': '抖音 Cookie 管理',
  '/admin/shortvideo/benchmark/accounts': '对标账号',
  '/admin/shortvideo/benchmark/videos': '对标视频',
  '/admin/shortvideo/benchmark/quality-scripts': '质量脚本库',
  '/admin/shortvideo/benchmark/recommendation': '脚本推荐',
  '/admin/copy/library': '文案库',
  '/admin/copy/templates': '文案模板',
  '/admin/copy/approval': '文案审批',
  '/admin/copy/all': '文案总览',
  '/admin/content/library': '内容库',
  '/org/copy/library': '文案库',
  '/org/copy/templates': '文案模板',
  '/org/copy/approval': '文案审批',
  '/org/copy/all': '文案总览',
  '/org/content/library': '内容库',
  '/admin/ai/knowledge': '知识库',
  '/admin/ai/knowledge-source': '知识来源',
  '/admin/ai/knowledge-search': '知识检索',
  '/admin/ai/dashboard': 'AI 仪表盘',
  '/admin/ai/evolution': '自进化引擎',
  '/admin/ai/knowledge-evolution': '进化监控看板',
  '/admin/ai/evolution-review': '进化审核',
  '/admin/ai/evolution-tasks': '进化任务',
  '/admin/ai/evolution-topics': '主题池',
  '/admin/ai/industry-brain': '行业大脑',
  '/admin/ai/industry-brain/diagnosis': '大脑诊断',
  '/admin/ai/brain-diagnosis': '大脑诊断',
  '/admin/ai/prompt-lab': 'Prompt 实验室',
  '/admin/ai/prompt-templates': 'Prompt 模板',
  '/admin/ai/prompt-tools': 'Prompt 工作台',
  '/admin/ai/models-config': '模型配置',
  '/admin/ai/admin-infra': 'AI 基础设施',
  '/admin/ai/viral-analysis': '进化爆款分析',
  '/admin/ai/creative-studio': '创意工坊',
  '/admin/ai/call-log': 'AI 调用日志',
  '/admin/ai/monitoring': 'AI 监控',
  '/admin/ai/digital-human': '数字人',
  '/admin/ai/model-benchmark': '模型基准测试',
  '/admin/ai/quota': 'AI 配额管理',
  '/admin/ai/task-model-config': '任务模型映射',
  '/admin/ai/agent/list': '智能体列表',
  '/admin/ai/agent/market': '智能体市场',
  '/admin/ai/agent/chat': '智能体对话',
  '/admin/ai/agent/workflow/list': '工作流编排',
  '/admin/ai/abtest/experiments': 'A/B 实验',
  '/admin/config': '系统配置',
  '/admin/storage': '文件存储',
  '/admin/system': '系统监控',
  '/admin/monitoring': '平台监控',
  '/admin/system/alert-rules': '告警规则',
  '/admin/system/api-log': 'API 日志',
  '/admin/system/compliance': '合规检测',
  '/admin/system/external-api': '外部 API 配置',
  '/admin/system/external-api-health': 'API 健康监控',
  '/admin/system/performance': '性能监控',
  '/admin/system/tianapi': '天 API 面板',
  '/admin/system/sync-log': '同步日志',
  '/admin/log/operations': '操作日志',
  '/admin/log/audit': '审计日志',
  '/admin/log/system': '系统日志',
  '/admin/wecom/robots': '企业微信机器人',
  '/admin/wecom': '企业微信',
  '/admin/wecom/rules': '推送规则',
  '/admin/payment/orders': '支付订单',
  '/admin/payment/subscription': '订阅管理',
  '/admin/payment/usage': '额度使用',
  '/admin/attribution': '归因分析',
  '/admin/slangdict': '俚语词典',
  '/admin/onboarding': '初始化引导',
  '/admin/kpi': '统一 KPI',
  '/org/members': '成员管理',
  '/org/analytics': '数据分析',
}

const GROUP_LABELS: Record<string, string> = {
  '/org': '机构',
  '/org/live': '直播',
  '/org/product': '商品',
  '/org/script': '话术内容',
  '/org/copy': '文案',
  '/org/content': '内容',
  '/talent': '达人',
  '/talent/shortvideo': '短视频',
  '/talent/douyin': '抖音',
  '/user': '普通用户',
  '/user/shortvideo': '短视频',
  '/admin/auth': '系统管理',
  '/admin/douyin': '运营管理',
  '/admin/live': '运营管理',
  '/admin/product': '运营管理',
  '/admin/script': '运营管理',
  '/admin/shortvideo': '运营管理',
  '/admin/copy': '运营管理',
  '/admin/ai': 'AI 中心',
  '/admin/ai/agent': 'AI 中心',
  '/admin/ai/abtest': 'AI 中心',
  '/admin/wecom': 'AI 中心',
  '/admin/config': '系统管理',
  '/admin/storage': '系统管理',
  '/admin/system': '系统管理',
  '/admin/log': '系统管理',
  '/admin/attribution': '系统管理',
  '/admin/payment': '支付',
  '/admin/onboarding': '系统管理',
  '/admin/kpi': '运营管理',
  '/admin/slangdict': '系统管理',
  '/admin/monitoring': '系统管理',
  '/admin/content': '运营管理',
}

const ROUTE_PATTERNS: Array<{ pattern: RegExp; label: string }> = [
  { pattern: /^\/admin\/douyin\/accounts\/[^/]+$/, label: '抖音账号详情' },
  { pattern: /^\/talent\/douyin\/accounts\/[^/]+$/, label: '抖音账号详情' },
  { pattern: /^\/admin\/live\/sessions\/[^/]+$/, label: '直播场次工作台' },
  { pattern: /^\/admin\/live\/sessions\/[^/]+\/edit$/, label: '编辑场次' },
  { pattern: /^\/admin\/live\/sessions\/[^/]+\/realtime$/, label: '实时面板' },
  { pattern: /^\/org\/live\/sessions\/[^/]+$/, label: '机构场次工作台' },
  { pattern: /^\/org\/live\/sessions\/[^/]+\/edit$/, label: '编辑场次' },
  { pattern: /^\/org\/live\/sessions\/[^/]+\/realtime$/, label: '实时面板' },
  { pattern: /^\/talent\/live\/sessions\/[^/]+$/, label: '达人场次工作台' },
  { pattern: /^\/admin\/product\/[^/]+\/scripts$/, label: '商品话术' },
  { pattern: /^\/admin\/product\/[^/]+\/script-versions$/, label: '话术版本' },
  { pattern: /^\/org\/product\/[^/]+\/scripts$/, label: '商品话术' },
  { pattern: /^\/org\/product\/[^/]+\/script-versions$/, label: '话术版本' },
  { pattern: /^\/admin\/shortvideo\/accounts\/[^/]+$/, label: '短视频账号详情' },
  { pattern: /^\/admin\/shortvideo\/benchmark\/analysis\/[^/]+$/, label: '对标分析详情' },
  { pattern: /^\/admin\/shortvideo\/benchmark\/quality-scripts\/[^/]+$/, label: '质量脚本详情' },
  { pattern: /^\/admin\/shortvideo\/subtitle-editor\/[^/]+$/, label: '字幕编辑' },
  { pattern: /^\/talent\/shortvideo\/accounts\/[^/]+$/, label: '短视频账号详情' },
  { pattern: /^\/talent\/shortvideo\/benchmark\/analysis\/[^/]+$/, label: '对标分析详情' },
  { pattern: /^\/talent\/shortvideo\/benchmark\/quality-scripts\/[^/]+$/, label: '质量脚本详情' },
  { pattern: /^\/talent\/shortvideo\/subtitle-editor\/[^/]+$/, label: '字幕编辑' },
  { pattern: /^\/admin\/ai\/knowledge\/[^/]+\/documents$/, label: '知识库文档' },
  { pattern: /^\/admin\/ai\/agent\/chat\/[^/]+$/, label: '智能体对话' },
  { pattern: /^\/admin\/ai\/agent\/share\/[^/]+$/, label: '智能体分享' },
  { pattern: /^\/admin\/ai\/agent\/workflow\/edit(?:\/[^/]+)?$/, label: '工作流编辑' },
  { pattern: /^\/admin\/ai\/abtest\/[^/]+$/, label: '实验详情' },
]

export interface Crumb { label: string; path?: string }

function normalizePathname(pathname: string): string {
  const normalized = pathname.split(/[?#]/)[0]?.replace(/\/+$/, '') || '/'
  return normalized
}

function findGroup(pathname: string): string | undefined {
  return Object.keys(GROUP_LABELS)
    .filter(k => pathname === k || pathname.startsWith(`${k}/`))
    .sort((a, b) => b.length - a.length)[0]
}

function findRouteLabel(pathname: string): string | undefined {
  return ROUTE_LABELS[pathname] ?? ROUTE_PATTERNS.find(item => item.pattern.test(pathname))?.label
}

function homeCrumb(pathname: string): Crumb {
  if (pathname === '/org' || pathname.startsWith('/org/')) return { label: '机构首页', path: '/org/dashboard' }
  if (pathname === '/talent' || pathname.startsWith('/talent/')) return { label: '达人首页', path: '/talent/dashboard' }
  if (pathname === '/user' || pathname.startsWith('/user/')) return { label: '普通用户首页', path: '/user/dashboard' }
  return { label: '首页', path: '/admin/dashboard' }
}

export function getBreadcrumbs(pathname: string): Crumb[] {
  const normalized = normalizePathname(pathname)
  if (normalized === '/admin/dashboard') return [{ label: '首页' }]
  if (normalized === '/org/dashboard') return [{ label: '机构' }, { label: '工作台' }]
  if (normalized === '/talent/dashboard') return [{ label: '达人' }, { label: '工作台' }]
  if (normalized === '/user/dashboard') return [{ label: '普通用户' }, { label: '工作台' }]
  const group = findGroup(normalized)
  const label = findRouteLabel(normalized)
  const crumbs: Crumb[] = [homeCrumb(normalized)]
  if (group) crumbs.push({ label: GROUP_LABELS[group] })
  if (label) crumbs.push({ label })
  return crumbs
}
