import { Navigate, type RouteObject } from 'react-router-dom'
import { ADMIN_AI_VIRAL_ANALYSIS_EVOLUTION, ADMIN_SHORTVIDEO_BASE, TALENT_SHORTVIDEO_BASE } from '@/constants/shortvideoRoutes'
import { AdminLayout } from '@/layouts/AdminLayout'
import {
  AdminInfraPage,
  AdminHomePage,
  AgentChatPage,
  AgentListPage,
  AgentMarketPage,
  AgentSharePage,
  AgentWorkflowEditorPage,
  AgentWorkflowListPage,
  AiCallLogPage,
  AiDashboardPage,
  AiMonitoringPage,
  AiRuntimeStatusPage,
  AiQuotaPage,
  AlertRulesPage,
  ApiLogPage,
  AuditLogPage,
  ComplianceCheckPage,
  ConfigPage,
  CreditGovernancePage,
  McpGatewayPage,
  OpenApiDeveloperPage,
  PaymentCenterPage,
  DouyinOpsCommanderPage,
  CreativeStudioPage,
  DigitalHumanPage,
  EvolutionPage,
  EvolutionReviewPage,
  EvolutionTasksPage,
  EvolutionTopicPage,
  ExperimentsPage,
  ExperimentDetailPage,
  ExternalApiConfigPage,
  ExternalApiHealthPage,
  IndustryBrainDiagnosisPage,
  IndustryBrainPage,
  KnowledgeBasePage,
  KnowledgeDocumentsPage,
  KnowledgeEvolutionPage,
  KnowledgeSearchPage,
  KnowledgeSourcePage,
  LazyRoute,
  LoginLogsPage,
  MetricsDashboard,
  ModelBenchmarkPage,
  ModelsConfigPage,
  OperationLogPage,
  OrdersPage,
  PerformanceMonitoringPage,
  PrefixRedirect,
  PromptLabPage,
  PromptTemplatePage,
  PromptToolsPage,
  ProfilePage,
  ResourcesPage,
  RolesPage,
  StoragePage,
  SubscriptionPage,
  SyncLogPage,
  SystemLogPage,
  SystemPage,
  TaskModelConfigPage,
  TianApiPanelPage,
  UnifiedKpiPage,
  UsageQuotaPage,
  UsersPage,
  ViralAnalysisPage,
  WecomPage,
  RobotsPage,
  RulesPage,
} from '../routeComponents'

export const adminRoutes: RouteObject = {
  path: '/admin',
  element: <AdminLayout />,
  children: [
    { index: true, element: <Navigate to="/admin/dashboard" replace /> },
    { path: 'dashboard', element: <LazyRoute element={<AdminHomePage />} /> },
    { path: 'profile', element: <LazyRoute element={<ProfilePage />} /> },
    { path: 'auth/users', element: <LazyRoute element={<UsersPage />} /> },
    { path: 'auth/roles', element: <LazyRoute element={<RolesPage />} /> },
    { path: 'auth/resources', element: <LazyRoute element={<ResourcesPage />} /> },
    { path: 'auth/login-logs', element: <LazyRoute element={<LoginLogsPage />} /> },
    { path: 'ai/dashboard', element: <LazyRoute element={<AiDashboardPage />} /> },
    { path: 'ai/knowledge', element: <LazyRoute element={<KnowledgeBasePage />} /> },
    { path: 'ai/knowledge-source', element: <LazyRoute element={<KnowledgeSourcePage />} /> },
    { path: 'ai/knowledge-search', element: <LazyRoute element={<KnowledgeSearchPage />} /> },
    { path: 'ai/knowledge/:kbId/documents', element: <LazyRoute element={<KnowledgeDocumentsPage />} /> },
    { path: 'ai/evolution', element: <LazyRoute element={<EvolutionPage />} /> },
    { path: 'ai/knowledge-evolution', element: <LazyRoute element={<KnowledgeEvolutionPage />} /> },
    { path: 'ai/evolution-review', element: <LazyRoute element={<EvolutionReviewPage />} /> },
    { path: 'ai/evolution-tasks', element: <LazyRoute element={<EvolutionTasksPage />} /> },
    { path: 'ai/evolution-topics', element: <LazyRoute element={<EvolutionTopicPage />} /> },
    { path: 'ai/industry-brain', element: <LazyRoute element={<IndustryBrainPage />} /> },
    { path: 'ai/industry-brain/diagnosis', element: <LazyRoute element={<IndustryBrainDiagnosisPage />} /> },
    { path: 'ai/brain-diagnosis', element: <LazyRoute element={<IndustryBrainDiagnosisPage />} /> },
    { path: 'ai/prompt-lab', element: <LazyRoute element={<PromptLabPage />} /> },
    { path: 'ai/prompt-templates', element: <LazyRoute element={<PromptTemplatePage />} /> },
    { path: 'ai/prompt-tools', element: <LazyRoute element={<PromptToolsPage />} /> },
    { path: 'ai/models-config', element: <LazyRoute element={<ModelsConfigPage />} /> },
    { path: 'ai/admin-infra', element: <LazyRoute element={<AdminInfraPage />} /> },
    { path: 'ai/model-benchmark', element: <LazyRoute element={<ModelBenchmarkPage />} /> },
    { path: 'ai/quota', element: <LazyRoute element={<AiQuotaPage />} /> },
    { path: 'ai/task-model-config', element: <LazyRoute element={<TaskModelConfigPage />} /> },
    { path: 'ai/viral-analysis', element: <LazyRoute element={<ViralAnalysisPage />} /> },
    { path: 'ai/creative-studio', element: <LazyRoute element={<CreativeStudioPage />} /> },
    { path: 'ai/call-log', element: <LazyRoute element={<AiCallLogPage />} /> },
    { path: 'ai/monitoring', element: <LazyRoute element={<AiMonitoringPage />} /> },
    { path: 'ai/runtime-status', element: <LazyRoute element={<AiRuntimeStatusPage />} /> },
    { path: 'ai/digital-human', element: <LazyRoute element={<DigitalHumanPage />} /> },
    { path: 'ai/agent/list', element: <LazyRoute element={<AgentListPage />} /> },
    { path: 'ai/agent/market', element: <LazyRoute element={<AgentMarketPage />} /> },
    { path: 'ai/agent/chat/:id', element: <LazyRoute element={<AgentChatPage />} /> },
    { path: 'ai/agent/share/:shareCode', element: <LazyRoute element={<AgentSharePage />} /> },
    { path: 'ai/agent/workflow/list', element: <LazyRoute element={<AgentWorkflowListPage />} /> },
    { path: 'ai/agent/workflow/edit/:id', element: <LazyRoute element={<AgentWorkflowEditorPage />} /> },
    { path: 'ai/agent/workflow/edit', element: <LazyRoute element={<AgentWorkflowEditorPage />} /> },
    { path: 'ai/abtest/experiments', element: <LazyRoute element={<ExperimentsPage />} /> },
    { path: 'ai/abtest/:id', element: <LazyRoute element={<ExperimentDetailPage />} /> },
    { path: 'config', element: <LazyRoute element={<ConfigPage />} /> },
    { path: 'storage', element: <LazyRoute element={<StoragePage />} /> },
    { path: 'system', element: <LazyRoute element={<SystemPage />} /> },
    { path: 'monitoring', element: <LazyRoute element={<MetricsDashboard />} /> },
    { path: 'system/alert-rules', element: <LazyRoute element={<AlertRulesPage />} /> },
    { path: 'system/api-log', element: <LazyRoute element={<ApiLogPage />} /> },
    { path: 'system/compliance', element: <LazyRoute element={<ComplianceCheckPage />} /> },
    { path: 'system/external-api', element: <LazyRoute element={<ExternalApiConfigPage />} /> },
    { path: 'system/external-api-health', element: <LazyRoute element={<ExternalApiHealthPage />} /> },
    { path: 'system/performance', element: <LazyRoute element={<PerformanceMonitoringPage />} /> },
    { path: 'system/tianapi', element: <LazyRoute element={<TianApiPanelPage />} /> },
    { path: 'system/sync-log', element: <LazyRoute element={<SyncLogPage />} /> },
    { path: 'log/operations', element: <LazyRoute element={<OperationLogPage />} /> },
    { path: 'log/audit', element: <LazyRoute element={<AuditLogPage />} /> },
    { path: 'log/system', element: <LazyRoute element={<SystemLogPage />} /> },
    { path: 'wecom', element: <LazyRoute element={<WecomPage />} /> },
    { path: 'wecom/robots', element: <LazyRoute element={<RobotsPage />} /> },
    { path: 'wecom/rules', element: <LazyRoute element={<RulesPage />} /> },
    { path: 'payment/orders', element: <LazyRoute element={<OrdersPage />} /> },
    { path: 'payment/subscription', element: <LazyRoute element={<SubscriptionPage />} /> },
    { path: 'payment/usage', element: <LazyRoute element={<UsageQuotaPage />} /> },
    { path: 'gaifan/credits', element: <LazyRoute element={<CreditGovernancePage />} /> },
    { path: 'gaifan/mcp', element: <LazyRoute element={<McpGatewayPage />} /> },
    { path: 'gaifan/openapi', element: <LazyRoute element={<OpenApiDeveloperPage />} /> },
    { path: 'gaifan/payment', element: <LazyRoute element={<PaymentCenterPage />} /> },
    { path: 'gaifan/douyin-ops-commander', element: <LazyRoute element={<DouyinOpsCommanderPage />} /> },
    { path: 'slangdict', element: <PrefixRedirect from="/admin/slangdict" to="/org/slangdict" /> },
    { path: 'kpi', element: <LazyRoute element={<UnifiedKpiPage />} /> },
    { path: 'shortvideo', element: <PrefixRedirect from={ADMIN_SHORTVIDEO_BASE} to={TALENT_SHORTVIDEO_BASE} /> },
    { path: 'shortvideo/*', element: <PrefixRedirect from={ADMIN_SHORTVIDEO_BASE} to={TALENT_SHORTVIDEO_BASE} /> },
    { path: 'live/*', element: <PrefixRedirect from="/admin/live" to="/org/live" /> },
    { path: 'product/*', element: <PrefixRedirect from="/admin/product" to="/org/product" /> },
    { path: 'script/*', element: <PrefixRedirect from="/admin/script" to="/org/script" /> },
    { path: 'copy/*', element: <PrefixRedirect from="/admin/copy" to="/org/copy" /> },
    { path: 'content/*', element: <PrefixRedirect from="/admin/content" to="/org/content" /> },
    { path: 'douyin/*', element: <PrefixRedirect from="/admin/douyin" to="/talent/douyin" /> },
    { path: 'attribution', element: <Navigate to={ADMIN_AI_VIRAL_ANALYSIS_EVOLUTION} replace /> },
  ],
}
