import { Navigate, type RouteObject } from 'react-router-dom'
import { OrgLayout } from '@/layouts/OrgLayout'
import {
  ContentLibraryPage,
  CopyApprovalPage,
  CopyLibraryPage,
  CopyPage,
  CopyTemplatePage,
  EffectivenessScorePage,
  HybridSearchPage,
  LazyRoute,
  LiveProductPage,
  LiveRealtimePanelPage,
  LiveScriptsPage,
  LiveSessionFormPage,
  LiveWorkbenchPage,
  MembersPage,
  OrgAnalyticsPage,
  OrgHomePage,
  OrgLiveReviewsPage,
  OrgLiveSessionPage,
  ProfilePage,
  ProductReadinessPage,
  ProductsPage,
  ProductScriptManagePage,
  ProductScriptVersionPage,
  RhythmPage,
  SalesHistoryPage,
  ScriptGenerationPage,
  ScriptListPage,
  ScriptOptimizationPage,
  ScriptRankingPage,
  ScriptTemplatePage,
  SessionWorkspacePageWrapper,
  SlangDictPage,
  StylePresetPage,
  ViolationCheckPage,
  ViolationWordPage,
  HistoryComparePage,
} from '../routeComponents'

export const orgRoutes: RouteObject = {
  path: '/org',
  element: <OrgLayout />,
  children: [
    { index: true, element: <Navigate to="/org/dashboard" replace /> },
    { path: 'dashboard', element: <LazyRoute element={<OrgHomePage />} /> },
    { path: 'profile', element: <LazyRoute element={<ProfilePage />} /> },
    { path: 'members', element: <LazyRoute element={<MembersPage />} /> },
    { path: 'analytics', element: <LazyRoute element={<OrgAnalyticsPage />} /> },
    { path: 'live/sessions', element: <LazyRoute element={<OrgLiveSessionPage />} /> },
    { path: 'live/sessions/create', element: <LazyRoute element={<LiveSessionFormPage />} /> },
    { path: 'live/sessions/:sessionId', element: <LazyRoute element={<SessionWorkspacePageWrapper />} /> },
    { path: 'live/sessions/:id/edit', element: <LazyRoute element={<LiveSessionFormPage />} /> },
    { path: 'live/sessions/:id/realtime', element: <LazyRoute element={<LiveRealtimePanelPage />} /> },
    { path: 'live/workbench/:sessionId', element: <LazyRoute element={<LiveWorkbenchPage />} /> },
    { path: 'live/reviews', element: <LazyRoute element={<OrgLiveReviewsPage />} /> },
    { path: 'live/scripts', element: <LazyRoute element={<LiveScriptsPage />} /> },
    { path: 'live/products', element: <LazyRoute element={<LiveProductPage />} /> },
    { path: 'live/ranking', element: <LazyRoute element={<ScriptRankingPage />} /> },
    { path: 'live/rhythm', element: <LazyRoute element={<RhythmPage />} /> },
    { path: 'live/history-compare', element: <LazyRoute element={<HistoryComparePage />} /> },
    { path: 'product', element: <LazyRoute element={<ProductsPage />} /> },
    { path: 'product/list', element: <LazyRoute element={<ProductsPage />} /> },
    { path: 'product/sales-history', element: <LazyRoute element={<SalesHistoryPage />} /> },
    { path: 'product/effectiveness', element: <LazyRoute element={<EffectivenessScorePage />} /> },
    { path: 'product/style-presets', element: <LazyRoute element={<StylePresetPage />} /> },
    { path: 'product/readiness', element: <LazyRoute element={<ProductReadinessPage />} /> },
    { path: 'product/:productId/scripts', element: <LazyRoute element={<ProductScriptManagePage />} /> },
    { path: 'product/:productId/script-versions', element: <LazyRoute element={<ProductScriptVersionPage />} /> },
    { path: 'script/list', element: <LazyRoute element={<ScriptListPage />} /> },
    { path: 'script/violation-words', element: <LazyRoute element={<ViolationWordPage />} /> },
    { path: 'script/violation-check', element: <LazyRoute element={<ViolationCheckPage />} /> },
    { path: 'script/templates', element: <LazyRoute element={<ScriptTemplatePage />} /> },
    { path: 'script/hybrid-search', element: <LazyRoute element={<HybridSearchPage />} /> },
    { path: 'script/generation', element: <LazyRoute element={<ScriptGenerationPage />} /> },
    { path: 'script/optimization', element: <LazyRoute element={<ScriptOptimizationPage />} /> },
    { path: 'copy/library', element: <LazyRoute element={<CopyLibraryPage />} /> },
    { path: 'copy/templates', element: <LazyRoute element={<CopyTemplatePage />} /> },
    { path: 'copy/approval', element: <LazyRoute element={<CopyApprovalPage />} /> },
    { path: 'copy/all', element: <LazyRoute element={<CopyPage />} /> },
    { path: 'content/library', element: <LazyRoute element={<ContentLibraryPage />} /> },
    { path: 'slangdict', element: <LazyRoute element={<SlangDictPage />} /> },
  ],
}
