import { Navigate, type RouteObject } from 'react-router-dom'
import { ADMIN_AI_VIRAL_ANALYSIS_EVOLUTION, shortvideoRoutes } from '@/constants/shortvideoRoutes'
import { TalentLayout } from '@/layouts/TalentLayout'
import { UserLayout } from '@/layouts/UserLayout'
import {
  AccountsPage,
  AccountCollectPage,
  AiMusicPage,
  BenchmarkAccountListPage,
  BenchmarkAnalysisDetailPage,
  BenchmarkQualityScriptDetailPage,
  BenchmarkQualityScriptListPage,
  BenchmarkScriptRecommendationPage,
  BenchmarkVideoListPage,
  CompetitorMonitorPage,
  ContentCalendarPage,
  ContentEffectPredictPage,
  DailyContentPage,
  DataAnalysisPage,
  DouyinAccountDetailPage,
  DouyinCookieManagePage,
  DramaPage,
  HotTopicCreationPage,
  HotTopicPage,
  LazyRoute,
  LiveWorkbenchPage,
  MaterialPage,
  MaterialPreparationPage,
  MaterialProductionPage,
  PersonaViralFusionPage,
  PhotoAvatarPage,
  ProfilePage,
  PublishPage,
  QualityPage,
  QuickGeneratePage,
  RemakeTemplatePage,
  ScriptPlanningPage,
  SeoOptimizePage,
  SessionsPage,
  ShotListPage,
  ShortVideoDashboardPage,
  ShortVideoInsightsHubPage,
  SubtitleEditorPage,
  SvAccountDetailPage,
  SvAccountListPage,
  SvProjectWorkbenchPage,
  TalentHomePage,
  TalentShortvideoEntry,
  UserHomePage,
  UserShortvideoPage,
  VideoEditingPage,
  VideosPage,
  ViralChainPage,
  ViralVideoPage,
  WorkflowEditorPage,
} from '../routeComponents'

export const talentRoutes: RouteObject = {
  path: '/talent',
  element: <TalentLayout />,
  children: [
    { index: true, element: <Navigate to="/talent/dashboard" replace /> },
    { path: 'dashboard', element: <LazyRoute element={<TalentHomePage />} /> },
    { path: 'profile', element: <LazyRoute element={<ProfilePage />} /> },
    { path: 'live/sessions', element: <LazyRoute element={<SessionsPage />} /> },
    { path: 'live/sessions/:sessionId', element: <LazyRoute element={<LiveWorkbenchPage />} /> },
    { path: 'douyin/accounts', element: <LazyRoute element={<AccountsPage />} /> },
    { path: 'douyin/accounts/:id', element: <LazyRoute element={<DouyinAccountDetailPage />} /> },
    { path: 'douyin/videos', element: <LazyRoute element={<VideosPage />} /> },
    { path: 'shortvideo', element: <TalentShortvideoEntry /> },
    { path: 'shortvideo/projects', element: <LazyRoute element={<TalentShortvideoEntry />} /> },
    { path: 'shortvideo/collect', element: <LazyRoute element={<AccountCollectPage />} /> },
    { path: 'shortvideo/accounts', element: <LazyRoute element={<SvAccountListPage />} /> },
    { path: 'shortvideo/accounts/:id', element: <LazyRoute element={<SvAccountDetailPage />} /> },
    { path: 'shortvideo/douyin-cookies', element: <LazyRoute element={<DouyinCookieManagePage />} /> },
    { path: 'shortvideo/benchmark/accounts', element: <LazyRoute element={<BenchmarkAccountListPage />} /> },
    { path: 'shortvideo/benchmark/videos', element: <LazyRoute element={<BenchmarkVideoListPage />} /> },
    { path: 'shortvideo/benchmark/analysis/:videoId', element: <LazyRoute element={<BenchmarkAnalysisDetailPage />} /> },
    { path: 'shortvideo/benchmark/quality-scripts', element: <LazyRoute element={<BenchmarkQualityScriptListPage />} /> },
    { path: 'shortvideo/benchmark/quality-scripts/:id', element: <LazyRoute element={<BenchmarkQualityScriptDetailPage />} /> },
    { path: 'shortvideo/benchmark/recommendation', element: <LazyRoute element={<BenchmarkScriptRecommendationPage />} /> },
    { path: 'shortvideo/remake-templates', element: <LazyRoute element={<RemakeTemplatePage />} /> },
    { path: 'shortvideo/viral-videos', element: <LazyRoute element={<ViralVideoPage />} /> },
    { path: 'shortvideo/shot-list', element: <LazyRoute element={<ShotListPage />} /> },
    { path: 'shortvideo/material', element: <LazyRoute element={<MaterialPage />} /> },
    { path: 'shortvideo/editing', element: <LazyRoute element={<VideoEditingPage />} /> },
    { path: 'shortvideo/publish', element: <LazyRoute element={<PublishPage />} /> },
    { path: 'shortvideo/quality', element: <LazyRoute element={<QualityPage />} /> },
    { path: 'shortvideo/daily', element: <LazyRoute element={<DailyContentPage />} /> },
    { path: 'shortvideo/viral-chain', element: <LazyRoute element={<ViralChainPage />} /> },
    { path: 'shortvideo/hot-topics/create', element: <LazyRoute element={<HotTopicCreationPage />} /> },
    { path: 'shortvideo/hot-topics', element: <LazyRoute element={<HotTopicPage />} /> },
    { path: 'shortvideo/content-calendar', element: <LazyRoute element={<ContentCalendarPage />} /> },
    { path: 'shortvideo/drama', element: <LazyRoute element={<DramaPage />} /> },
    { path: 'shortvideo/competitor-monitor', element: <LazyRoute element={<CompetitorMonitorPage />} /> },
    { path: 'shortvideo/effect-predict', element: <LazyRoute element={<ContentEffectPredictPage />} /> },
    { path: 'shortvideo/data-analysis', element: <LazyRoute element={<DataAnalysisPage />} /> },
    { path: 'shortvideo/dashboard', element: <LazyRoute element={<ShortVideoDashboardPage />} /> },
    { path: 'shortvideo/insights', element: <LazyRoute element={<ShortVideoInsightsHubPage />} /> },
    { path: 'shortvideo/viral-analysis', element: <Navigate to={ADMIN_AI_VIRAL_ANALYSIS_EVOLUTION} replace /> },
    { path: 'shortvideo/quick-generate', element: <LazyRoute element={<QuickGeneratePage />} /> },
    { path: 'shortvideo/script-planning', element: <LazyRoute element={<ScriptPlanningPage />} /> },
    { path: 'shortvideo/material-prepare', element: <LazyRoute element={<MaterialPreparationPage />} /> },
    { path: 'shortvideo/material-production', element: <LazyRoute element={<MaterialProductionPage />} /> },
    { path: 'shortvideo/workbench', element: <LazyRoute element={<SvProjectWorkbenchPage />} /> },
    { path: 'shortvideo/workflow-editor', element: <LazyRoute element={<WorkflowEditorPage />} /> },
    { path: 'shortvideo/subtitles', element: <LazyRoute element={<VideoEditingPage />} /> },
    { path: 'shortvideo/subtitle-editor/:id', element: <LazyRoute element={<SubtitleEditorPage />} /> },
    { path: 'shortvideo/persona-fusion', element: <LazyRoute element={<PersonaViralFusionPage />} /> },
    { path: 'shortvideo/ai-music', element: <LazyRoute element={<AiMusicPage />} /> },
    { path: 'shortvideo/photo-avatar', element: <LazyRoute element={<PhotoAvatarPage />} /> },
    { path: 'shortvideo/seo', element: <Navigate to={shortvideoRoutes.seoOptimize} replace /> },
    { path: 'shortvideo/seo-optimize', element: <LazyRoute element={<SeoOptimizePage />} /> },
  ],
}

export const userRoutes: RouteObject = {
  path: '/user',
  element: <UserLayout />,
  children: [
    { index: true, element: <Navigate to="/user/dashboard" replace /> },
    { path: 'dashboard', element: <LazyRoute element={<UserHomePage />} /> },
    { path: 'profile', element: <LazyRoute element={<ProfilePage />} /> },
    { path: 'shortvideo', element: <LazyRoute element={<UserShortvideoPage />} /> },
    { path: 'shortvideo/create', element: <LazyRoute element={<UserShortvideoPage />} /> },
    { path: 'shortvideo/planning', element: <LazyRoute element={<UserShortvideoPage />} /> },
    { path: 'shortvideo/materials', element: <LazyRoute element={<UserShortvideoPage />} /> },
    { path: 'shortvideo/publish', element: <LazyRoute element={<UserShortvideoPage />} /> },
  ],
}
