import { lazy, Suspense } from 'react'
import { Navigate, useLocation } from 'react-router-dom'
import { PageSkeleton } from '@/components/base'

export const LoginPage = lazy(() => import('@/pages/LoginPage'))
export const OfficialWebsitePage = lazy(() => import('@/pages/gaifan/OfficialWebsitePage'))
export const CreditGovernancePage = lazy(() => import('@/pages/gaifan/CreditGovernancePage'))
export const McpGatewayPage = lazy(() => import('@/pages/gaifan/McpGatewayPage'))
export const OpenApiDeveloperPage = lazy(() => import('@/pages/gaifan/OpenApiDeveloperPage'))
export const DocsCenterPage = lazy(() => import('@/pages/gaifan/DocsCenterPage'))
export const PaymentCenterPage = lazy(() => import('@/pages/gaifan/PaymentCenterPage'))
export const DouyinOpsCommanderPage = lazy(() => import('@/pages/gaifan/DouyinOpsCommanderPage'))
export const NotFoundPage = lazy(() => import('@/pages/NotFoundPage'))
export const DashboardPage = lazy(() => import('@/pages/DashboardPage'))
export const AdminHomePage = lazy(() => import('@/pages/admin/AdminHomePage'))
export const OrgHomePage = lazy(() => import('@/pages/org/OrgHomePage'))
export const TalentHomePage = lazy(() => import('@/pages/talent/TalentHomePage'))
export const UserHomePage = lazy(() => import('@/pages/user/UserHomePage'))
export const ProfilePage = lazy(() => import('@/pages/profile/ProfilePage'))
export const UserShortvideoPage = lazy(() => import('@/pages/user/UserShortvideoPage'))
export const UsersPage = lazy(() => import('@/pages/auth/UsersPage'))
export const RolesPage = lazy(() => import('@/pages/auth/RolesPage'))
export const LoginLogsPage = lazy(() => import('@/pages/auth/LoginLogsPage'))
export const AccountsPage = lazy(() => import('@/pages/douyin/AccountsPage'))
export const VideosPage = lazy(() => import('@/pages/douyin/VideosPage'))
export const SessionsPage = lazy(() => import('@/pages/live/SessionsPage'))
export const LiveScriptsPage = lazy(() => import('@/pages/live/ScriptsPage'))
export const LiveWorkbenchPage = lazy(() => import('@/pages/live/LiveWorkbenchPage'))
export const SessionWorkspacePageWrapper = lazy(() => import('@/pages/live/SessionWorkspacePage'))
export const ProductsPage = lazy(() => import('@/pages/product/ProductsPage'))
export const ScriptListPage = lazy(() => import('@/pages/script/ScriptListPage'))
export const ViolationWordPage = lazy(() => import('@/pages/script/ViolationWordPage'))
export const ProjectsPage = lazy(() => import('@/pages/shortvideo/ProjectsPage'))
export const AccountCollectPage = lazy(() => import('@/pages/shortvideo/AccountCollectPage'))
export const SvAccountListPage = lazy(() => import('@/pages/shortvideo/SvAccountListPage'))
export const SvAccountDetailPage = lazy(() => import('@/pages/shortvideo/SvAccountDetailPage'))
export const DouyinCookieManagePage = lazy(() => import('@/pages/benchmark/DouyinCookieManagePage'))
export const BenchmarkAccountListPage = lazy(() => import('@/pages/benchmark/BenchmarkAccountListPage'))
export const BenchmarkVideoListPage = lazy(() => import('@/pages/benchmark/BenchmarkVideoListPage'))
export const BenchmarkAnalysisDetailPage = lazy(() => import('@/pages/benchmark/BenchmarkAnalysisDetailPage'))
export const BenchmarkQualityScriptListPage = lazy(() => import('@/pages/benchmark/BenchmarkQualityScriptListPage'))
export const BenchmarkQualityScriptDetailPage = lazy(() => import('@/pages/benchmark/BenchmarkQualityScriptDetailPage'))
export const BenchmarkScriptRecommendationPage = lazy(() => import('@/pages/benchmark/BenchmarkScriptRecommendationPage'))
export const RemakeTemplatePage = lazy(() => import('@/pages/shortvideo/RemakeTemplatePage'))
export const CopyLibraryPage = lazy(() => import('@/pages/copy/CopyLibraryPage'))
export const CopyTemplatePage = lazy(() => import('@/pages/copy/CopyTemplatePage'))
export const KnowledgeBasePage = lazy(() => import('@/pages/ai/KnowledgeBasePage'))
export const KnowledgeSourcePage = lazy(() => import('@/pages/ai/KnowledgeSourcePage'))
export const EvolutionPage = lazy(() => import('@/pages/ai/EvolutionPage'))
export const AgentListPage = lazy(() => import('@/pages/agent/AgentListPage'))
export const AgentMarketPage = lazy(() => import('@/pages/agent/AgentMarketPage'))
export const ExperimentsPage = lazy(() => import('@/pages/abtest/ExperimentsPage'))
export const ConfigPage = lazy(() => import('@/pages/config/ConfigPage'))
export const StoragePage = lazy(() => import('@/pages/storage/StoragePage'))
export const SystemPage = lazy(() => import('@/pages/system/SystemPage'))
export const OperationLogPage = lazy(() => import('@/pages/log/OperationLogPage'))
export const AuditLogPage = lazy(() => import('@/pages/log/AuditLogPage'))
export const MetricsDashboard = lazy(() => import('@/pages/monitoring/MetricsDashboard'))
export const WecomPage = lazy(() => import('@/pages/wecom/WecomPage'))
export const RobotsPage = lazy(() => import('@/pages/wecom/RobotsPage'))
export const RulesPage = lazy(() => import('@/pages/wecom/RulesPage'))
export const OrdersPage = lazy(() => import('@/pages/payment/OrdersPage'))
export const SubscriptionPage = lazy(() => import('@/pages/payment/SubscriptionPage'))
export const UsageQuotaPage = lazy(() => import('@/pages/payment/UsageQuotaPage'))
export const AttributionPage = lazy(() => import('@/pages/attribution/AttributionPage'))
export const ResourcesPage = lazy(() => import('@/pages/auth/ResourcesPage'))
export const ScriptRankingPage = lazy(() => import('@/pages/live/ScriptRankingPage'))
export const RhythmPage = lazy(() => import('@/pages/live/RhythmPage'))
export const HistoryComparePage = lazy(() => import('@/pages/live/HistoryComparePage'))
export const CopyApprovalPage = lazy(() => import('@/pages/copy/CopyApprovalPage'))
export const ScriptTemplatePage = lazy(() => import('@/pages/script/ScriptTemplatePage'))
export const AlertRulesPage = lazy(() => import('@/pages/system/AlertRulesPage'))
export const ApiLogPage = lazy(() => import('@/pages/system/ApiLogPage'))
export const AiDashboardPage = lazy(() => import('@/pages/ai/AiDashboardPage'))
export const KnowledgeSearchPage = lazy(() => import('@/pages/ai/KnowledgeSearchPage'))
export const KnowledgeDocumentsPage = lazy(() => import('@/pages/ai/KnowledgeDocumentsPage'))
export const ComplianceCheckPage = lazy(() => import('@/pages/system/ComplianceCheckPage'))
export const ExternalApiConfigPage = lazy(() => import('@/pages/system/ExternalApiConfigPage'))
export const ViralVideoPage = lazy(() => import('@/pages/shortvideo/ViralVideoPage'))
export const PromptTemplatePage = lazy(() => import('@/pages/ai/PromptTemplatePage'))
export const ViralAnalysisPage = lazy(() => import('@/pages/ai/ViralAnalysisPage'))
export const CreativeStudioPage = lazy(() => import('@/pages/ai/CreativeStudioPage'))
export const AiCallLogPage = lazy(() => import('@/pages/ai/AiCallLogPage'))
export const AiMonitoringPage = lazy(() => import('@/pages/ai/AiMonitoringPage'))
export const AiRuntimeStatusPage = lazy(() => import('@/pages/ai/AiRuntimeStatusPage'))
export const DigitalHumanPage = lazy(() => import('@/pages/ai/DigitalHumanPage'))
export const AgentChatPage = lazy(() => import('@/pages/agent/AgentChatPage'))
export const AgentSharePage = lazy(() => import('@/pages/agent/AgentSharePage'))
export const AgentWorkflowListPage = lazy(() => import('@/pages/agent/AgentWorkflowListPage'))
export const AgentWorkflowEditorPage = lazy(() => import('@/pages/agent/AgentWorkflowEditorPage'))
export const ExperimentDetailPage = lazy(() => import('@/pages/abtest/ExperimentDetailPage'))
export const MembersPage = lazy(() => import('@/pages/org/MembersPage'))
export const OrgAnalyticsPage = lazy(() => import('@/pages/org/OrgAnalyticsPage'))
export const OrgLiveReviewsPage = lazy(() => import('@/pages/org/OrgLiveReviewsPage'))
export const LiveSessionFormPage = lazy(() => import('@/pages/live/LiveSessionFormPage'))
export const LiveRealtimePanelPage = lazy(() => import('@/pages/live/LiveRealtimePanelPage'))
export const LiveProductPage = lazy(() => import('@/pages/live/LiveProductPage'))
export const OrgLiveSessionPage = lazy(() => import('@/pages/live/OrgLiveSessionPage'))
export const ProductScriptVersionPage = lazy(() => import('@/pages/product/ProductScriptVersionPage'))
export const ProductScriptManagePage = lazy(() => import('@/pages/product/ProductScriptManagePage'))
export const HybridSearchPage = lazy(() => import('@/pages/script/HybridSearchPage'))
export const OnboardingPage = lazy(() => import('@/pages/onboarding/OnboardingPage'))
export const UnifiedKpiPage = lazy(() => import('@/pages/UnifiedKpiPage'))
export const ShotListPage = lazy(() => import('@/pages/shortvideo/ShotListPage'))
export const MaterialPage = lazy(() => import('@/pages/shortvideo/MaterialPage'))
export const VideoEditingPage = lazy(() => import('@/pages/shortvideo/VideoEditingPage'))
export const PublishPage = lazy(() => import('@/pages/shortvideo/PublishPage'))
export const QualityPage = lazy(() => import('@/pages/shortvideo/QualityPage'))
export const DailyContentPage = lazy(() => import('@/pages/shortvideo/DailyContentPage'))
export const KnowledgeEvolutionPage = lazy(() => import('@/pages/ai/KnowledgeEvolutionPage'))
export const EvolutionReviewPage = lazy(() => import('@/pages/ai/EvolutionReviewPage'))
export const IndustryBrainPage = lazy(() => import('@/pages/ai/IndustryBrainPage'))
export const PromptLabPage = lazy(() => import('@/pages/ai/PromptLabPage'))
export const ModelsConfigPage = lazy(() => import('@/pages/ai/ModelsConfigPage'))
export const AdminInfraPage = lazy(() => import('@/pages/ai/AdminInfraPage'))
export const ViralChainPage = lazy(() => import('@/pages/shortvideo/ViralChainPage'))
export const HotTopicPage = lazy(() => import('@/pages/shortvideo/HotTopicPage'))
export const HotTopicCreationPage = lazy(() => import('@/pages/shortvideo/HotTopicCreationPage'))
export const ContentCalendarPage = lazy(() => import('@/pages/shortvideo/ContentCalendarPage'))
export const DramaPage = lazy(() => import('@/pages/shortvideo/DramaPage'))
export const ExternalApiHealthPage = lazy(() => import('@/pages/system/ExternalApiHealthPage'))
export const PerformanceMonitoringPage = lazy(() => import('@/pages/system/PerformanceMonitoringPage'))
export const TianApiPanelPage = lazy(() => import('@/pages/system/TianApiPanelPage'))
export const EffectivenessScorePage = lazy(() => import('@/pages/product/EffectivenessScorePage'))
export const StylePresetPage = lazy(() => import('@/pages/product/StylePresetPage'))
export const SlangDictPage = lazy(() => import('@/pages/slangdict/SlangDictPage'))
export const EvolutionTasksPage = lazy(() => import('@/pages/ai/EvolutionTasksPage'))
export const EvolutionTopicPage = lazy(() => import('@/pages/ai/EvolutionTopicPage'))
export const ViolationCheckPage = lazy(() => import('@/pages/script/ViolationCheckPage'))
export const ModelBenchmarkPage = lazy(() => import('@/pages/ai/ModelBenchmarkPage'))
export const IndustryBrainDiagnosisPage = lazy(() => import('@/pages/ai/IndustryBrainDiagnosisPage'))
export const PromptToolsPage = lazy(() => import('@/pages/ai/PromptToolsPage'))
export const ScriptGenerationPage = lazy(() => import('@/pages/script/ScriptGenerationPage'))
export const ScriptOptimizationPage = lazy(() => import('@/pages/script/ScriptOptimizationPage'))
export const CompetitorMonitorPage = lazy(() => import('@/pages/shortvideo/CompetitorMonitorPage'))
export const ContentEffectPredictPage = lazy(() => import('@/pages/shortvideo/ContentEffectPredictPage'))
export const DataAnalysisPage = lazy(() => import('@/pages/shortvideo/DataAnalysisPage'))
export const ShortVideoDashboardPage = lazy(() => import('@/pages/shortvideo/ShortVideoDashboardPage'))
export const ShortVideoInsightsHubPage = lazy(() => import('@/pages/shortvideo/ShortVideoInsightsHubPage'))
export const AiQuotaPage = lazy(() => import('@/pages/ai/AiQuotaPage'))
export const TaskModelConfigPage = lazy(() => import('@/pages/ai/TaskModelConfigPage'))
export const QuickGeneratePage = lazy(() => import('@/pages/shortvideo/QuickGeneratePage'))
export const ScriptPlanningPage = lazy(() => import('@/pages/shortvideo/ScriptPlanningPage'))
export const MaterialPreparationPage = lazy(() => import('@/pages/shortvideo/MaterialPreparationPage'))
export const MaterialProductionPage = lazy(() => import('@/pages/shortvideo/MaterialProductionPage'))
export const SvProjectWorkbenchPage = lazy(() => import('@/pages/shortvideo/SvProjectWorkbenchPage'))
export const WorkflowEditorPage = lazy(() => import('@/pages/shortvideo/WorkflowEditorPage'))
export const SubtitleEditorPage = lazy(() => import('@/pages/shortvideo/SubtitleEditorPage'))
export const PersonaViralFusionPage = lazy(() => import('@/pages/shortvideo/PersonaViralFusionPage'))
export const AiMusicPage = lazy(() => import('@/pages/shortvideo/AiMusicPage'))
export const SeoOptimizePage = lazy(() => import('@/pages/shortvideo/SeoOptimizePage'))
export const ProductReadinessPage = lazy(() => import('@/pages/product/ProductReadinessPage'))
export const DouyinAccountDetailPage = lazy(() => import('@/pages/douyin/DouyinAccountDetailPage'))
export const SalesHistoryPage = lazy(() => import('@/pages/product/SalesHistoryPage'))
export const SyncLogPage = lazy(() => import('@/pages/system/SyncLogPage'))
export const SystemLogPage = lazy(() => import('@/pages/log/SystemLogPage'))
export const ContentLibraryPage = lazy(() => import('@/pages/content/ContentLibraryPage'))
export const CopyPage = lazy(() => import('@/pages/copy/CopyPage'))
export const PhotoAvatarPage = lazy(() => import('@/pages/ai/PhotoAvatarPage'))

export function LazyRoute({ element }: { element: React.ReactNode }) {
  return <Suspense fallback={<PageSkeleton />}>{element}</Suspense>
}

export function TalentShortvideoEntry() {
  const location = useLocation()
  const searchParams = new URLSearchParams(location.search)
  const projectId = searchParams.get('projectId')?.trim()
  return projectId ? <LazyRoute element={<SvProjectWorkbenchPage />} /> : <LazyRoute element={<ProjectsPage />} />
}

export function PrefixRedirect({ from, to }: { from: string; to: string }) {
  const location = useLocation()
  const suffix = location.pathname.startsWith(from) ? location.pathname.slice(from.length) : ''
  return <Navigate to={`${to}${suffix}${location.search}${location.hash}`} replace />
}
