-- V057: Phase 5 P1-5 BGM 素材库补充至 50+ 条（V056 已有 11 条）
DO $$
BEGIN
  IF (SELECT COUNT(*) FROM sv_bgm_library WHERE deleted = 0) < 50 THEN
    INSERT INTO sv_bgm_library (bgm_name, artist, style, bpm, mood, energy_level, emotion_curve_match, license_type, duration_seconds, tags, deleted) VALUES
    ('Soft Rain', 'Ambient Dreams', 'chill_lofi', 70, '宁静', 2, 'slow_build', 'free', 220, '["护肤","冥想","放松"]'::jsonb, 0),
    ('Urban Night', 'City Beats', 'chill_lofi', 82, '慵懒', 3, 'suspense', 'free', 195, '["日常","vlog","城市"]'::jsonb, 0),
    ('Golden Hour', 'Sunset Keys', 'luxury_piano', 75, '温暖', 4, 'emotional_wave', 'free', 185, '["种草","情感","分享"]'::jsonb, 0),
    ('Ocean Breeze', 'Nature Sounds', 'luxury_piano', 68, '治愈', 3, 'slow_build', 'free', 240, '["护肤","自然","放松"]'::jsonb, 0),
    ('Dream Catcher', 'Piano Dreams', 'luxury_piano', 72, '梦幻', 3, 'suspense', 'free', 200, '["测评","种草","成分"]'::jsonb, 0),
    ('Spring Waltz', 'Classical Light', 'emotional_strings', 88, '欢快', 5, 'rollercoaster', 'free', 175, '["日常","分享","好物"]'::jsonb, 0),
    ('Autumn Leaves', 'String Ensemble', 'emotional_strings', 78, '感伤', 4, 'emotional_wave', 'free', 210, '["故事","情感","种草"]'::jsonb, 0),
    ('Midnight Drive', 'Synth Wave', 'upbeat_pop', 118, '活力', 7, 'hook_climax', 'free', 155, '["促销","活动","限时"]'::jsonb, 0),
    ('Neon Lights', 'Pop Factory', 'upbeat_pop', 130, '兴奋', 8, 'rollercoaster', 'free', 125, '["秒杀","福利","抽奖"]'::jsonb, 0),
    ('Summer Vibes', 'Beach Sounds', 'energetic_folk', 115, '轻松', 6, 'hook_climax', 'free', 165, '["日常","好物","推荐"]'::jsonb, 0),
    ('Mountain Echo', 'Folk Vibes', 'energetic_folk', 108, '自由', 6, 'rollercoaster', 'free', 170, '["旅行","分享","开箱"]'::jsonb, 0),
    ('Starlight', 'Piano Moods', 'luxury_piano', 65, '浪漫', 3, 'slow_build', 'free', 230, '["种草","情感","护肤"]'::jsonb, 0),
    ('Winter Warmth', 'Soft Keys', 'luxury_piano', 70, '温馨', 4, 'emotional_wave', 'free', 190, '["护肤","日常","vlog"]'::jsonb, 0),
    ('Tech Flow', 'Electronic Dreams', 'chill_lofi', 90, '专注', 4, 'suspense', 'free', 250, '["教程","科普","成分"]'::jsonb, 0),
    ('Cozy Cafe', 'Acoustic Life', 'energetic_folk', 95, '惬意', 5, 'slow_build', 'free', 180, '["日常","好物","推荐"]'::jsonb, 0),
    ('Rising Sun', 'Orchestra Light', 'emotional_strings', 92, '希望', 6, 'hook_climax', 'free', 195, '["故事","种草","情感"]'::jsonb, 0),
    ('Pulse', 'Beat Makers', 'upbeat_pop', 138, '激昂', 9, 'rollercoaster', 'free', 115, '["促销","秒杀","限时"]'::jsonb, 0),
    ('Quiet Storm', 'Piano Dreams', 'luxury_piano', 74, '内敛', 3, 'suspense', 'free', 205, '["精华","成分","科普"]'::jsonb, 0),
    ('Fresh Start', 'Folk Vibes', 'energetic_folk', 122, '清新', 7, 'hook_climax', 'free', 150, '["日常","分享","开箱"]'::jsonb, 0),
    ('Eternal Love', 'String Ensemble', 'emotional_strings', 86, '深情', 5, 'emotional_wave', 'free', 200, '["故事","种草","情感"]'::jsonb, 0),
    ('Power Hour', 'Pop Factory', 'upbeat_pop', 132, '爆发', 9, 'rollercoaster', 'free', 120, '["活动","福利","抽奖"]'::jsonb, 0),
    ('Serenity', 'Piano Moods', 'luxury_piano', 66, '平和', 2, 'slow_build', 'free', 235, '["护肤","冥想","放松"]'::jsonb, 0),
    ('Happy Days', 'Acoustic Life', 'energetic_folk', 112, '愉悦', 6, 'rollercoaster', 'free', 155, '["日常","好物","推荐"]'::jsonb, 0),
    ('Deep Dive', 'Chill Hop', 'chill_lofi', 76, '沉浸', 3, 'suspense', 'free', 260, '["教程","科普","成分"]'::jsonb, 0),
    ('Sparkle', 'Orchestra Light', 'emotional_strings', 94, '闪耀', 6, 'hook_climax', 'free', 175, '["种草","测评","护肤"]'::jsonb, 0),
    ('Rush Hour', 'Beat Makers', 'upbeat_pop', 140, '紧迫', 9, 'rollercoaster', 'free', 110, '["促销","秒杀","限时"]'::jsonb, 0),
    ('Gentle Wind', 'Soft Keys', 'luxury_piano', 69, '轻柔', 2, 'slow_build', 'free', 215, '["护肤","日常","vlog"]'::jsonb, 0),
    ('Wild Heart', 'Folk Vibes', 'energetic_folk', 125, '奔放', 7, 'rollercoaster', 'free', 145, '["分享","开箱","日常"]'::jsonb, 0),
    ('Mystery', 'Piano Dreams', 'luxury_piano', 64, '神秘', 3, 'suspense', 'free', 225, '["成分","科普","精华"]'::jsonb, 0),
    ('Joy Ride', 'Pop Factory', 'upbeat_pop', 128, '畅快', 8, 'hook_climax', 'free', 130, '["促销","活动","福利"]'::jsonb, 0),
    ('Peaceful Mind', 'Ambient Dreams', 'chill_lofi', 72, '安详', 2, 'slow_build', 'free', 245, '["护肤","冥想","放松"]'::jsonb, 0),
    ('Bright Future', 'String Ensemble', 'emotional_strings', 96, '明朗', 6, 'hook_climax', 'free', 185, '["种草","故事","情感"]'::jsonb, 0),
    ('Night Owl', 'Lofi Beats', 'chill_lofi', 80, '夜猫', 3, 'suspense', 'free', 255, '["教程","科普","日常"]'::jsonb, 0),
    ('Fireworks', 'Beat Makers', 'upbeat_pop', 142, '绚烂', 9, 'rollercoaster', 'free', 105, '["活动","福利","抽奖"]'::jsonb, 0),
    ('Morning Dew', 'Piano Moods', 'luxury_piano', 67, '清新', 3, 'slow_build', 'free', 220, '["护肤","日常","vlog"]'::jsonb, 0),
    ('Road Trip', 'Acoustic Life', 'energetic_folk', 118, '冒险', 7, 'rollercoaster', 'free', 160, '["旅行","分享","开箱"]'::jsonb, 0),
    ('Tender Moment', 'Orchestra Light', 'emotional_strings', 84, '温柔', 5, 'emotional_wave', 'free', 195, '["故事","种草","情感"]'::jsonb, 0),
    ('Flash Sale', 'Pop Factory', 'upbeat_pop', 135, '抢购', 9, 'hook_climax', 'free', 118, '["促销","秒杀","限时"]'::jsonb, 0),
    ('Zen Garden', 'Ambient Dreams', 'chill_lofi', 68, '禅意', 2, 'slow_build', 'free', 270, '["护肤","冥想","放松"]'::jsonb, 0),
    ('Sunrise', 'Folk Vibes', 'energetic_folk', 110, '朝气', 6, 'hook_climax', 'free', 170, '["日常","好物","推荐"]'::jsonb, 0),
    ('Elegant', 'String Ensemble', 'emotional_strings', 82, '优雅', 5, 'slow_build', 'free', 205, '["种草","测评","护肤"]'::jsonb, 0),
    ('Thunder', 'Beat Makers', 'upbeat_pop', 145, '震撼', 9, 'rollercoaster', 'free', 100, '["活动","福利","抽奖"]'::jsonb, 0);
  END IF;
END $$;
